modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/aurilisdev/Modular-Forcefields" #optional
[[mods]] #mandatory
modId="modularforcefields" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Modular Forcefields" #mandatory
displayURL="https://github.com/aurilisdev/Modular-Forcefields" #optional
logoFile="modularforcefields.png" #optional
credits="Thanks to all contributors" #optional
authors="aurilisdev" #optional
description='''
'''
[[dependencies.nuclearscience]]
    modId="electrodynamics"
    mandatory=true
    versionRange="[1.18.1-0.6,)"
    ordering="NONE"
    side="BOTH"